SELECT CART_ID
FROM
(SELECT T2.ID, T2.CART_ID, COUNT(T2.NAME) AS YOGURT_COUNT
FROM
(SELECT T1.ID, T1.CART_ID AS CART_ID, T1.NAME AS NAME
FROM (SELECT ID, CART_ID, NAME FROM CART_PRODUCTS WHERE NAME IN ('Yogurt', 'Milk')) T1) T2
WHERE T2.NAME = 'Yogurt'
GROUP BY T2.CART_ID) T5
JOIN
(SELECT T4.ID, T4.CART_ID, COUNT(T4.NAME) AS MILK_COUNT
FROM
(SELECT T3.ID, T3.CART_ID AS CART_ID, T3.NAME AS NAME
FROM (SELECT ID, CART_ID, NAME FROM CART_PRODUCTS WHERE NAME IN ('Yogurt', 'Milk')) T3) T4
WHERE T4.NAME = 'Milk'
GROUP BY T4.CART_ID) T6
USING (CART_ID)
WHERE YOGURT_COUNT >= 1 and MILK_COUNT >= 1
ORDER BY CART_ID